---

- ldap_attr:
    dn: "olcDatabase={1}mdb,cn=config"
    name: olcAccess
    values:
      - >-
        {0}to attrs=userPassword
        by self write
        by anonymous auth
        by dn="cn=admin,{{ ldap['basedn'] }}" write
        by * none
      - >-
        {1}to dn.base=""
        by * read
      - >-
        {2}to *
        by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
        by * break
      - >-
        {3}to dn.base="cn=Subschema"
        by * read
      - >-
        {4}to *
        by dn.exact="cn=idpuser,ou=system,{{ ldap['basedn'] }}" read
        by anonymous auth
        by self read
    state: exact
