---

- name: "Be sure to configure olcSizeLimit to 'unlimited'"
  ldap_attr:
   dn: "{{ item.dn }}"
   name: olcSizeLimit
   values: "unlimited"
   state: exact
  with_items:
   - { dn: "cn=config" }
   - { dn: "olcDatabase={-1}frontend,cn=config" }
