---

# Ansible < 2.9
#- name: "Be sure to configure olcLogLevel"
#  ldap_attr:
#   dn: "cn=config"
#   name: olcLogLevel
#   values: 256
#   state: exact 

# Ansible >= 2.10
- name: "Be sure to configure olcLogLevel"
  community.general.ldap_attrs:
   dn: "cn=config"
   attributes: 
    olcLogLevel: 256
   state: exact 
