---
# tasks file for openldap
- name: "Include Default OS variables if custom ones are not provided on the host_vars of IdP"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: openldap

- name: "Be sure that the package 'debconf-utils' and 'python-ldap' is installed"
  apt: 
   name: "{{ item }}"
   state: latest
   update_cache: yes
  with_items:
   - debconf-utils
   - python-ldap
  notify:
   - "Safe Upgrade"
  tags: openldap

- name: "Check if debconf-get-selections has parameters for unattended OpenLDAP installation and store the result on 'debconf' ansible variable"
  shell: (debconf-get-selections | grep -q -s slapd); echo $?
  register: debconf
  ignore_errors: yes
  changed_when: false
  tags: openldap

- name: "Be sure that OpenLDAP unattended installation parameters are set correctly"
  debconf:
    name: "slapd"
    question: "{{ item.key }}"
    vtype: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: slapd/password1
      type: password
      value: "{{ ldap['root_pw']|default('') }}"
    - key: slapd/password2
      type: password
      value: "{{ ldap['root_pw']|default('') }}"
    - key: slapd/move_old_database
      type: boolean
      value: true
    - key: slapd/domain
      type: string
      value: "{{ ldap['domain']|default('') }}"
    - key: shared/organization
      type: string
      value: "{{ ldap['org']|default('') }}"
    - key: slapd/no_configuration
      type: boolean
      value: false
    - key: slapd/purge_database
      type: boolean
      value: false
    - key: slapd/allow_ldap_v2
      type: boolean
      value: false
    - key: slapd/backend
      type: select
      value: MDB
  when: debconf.stdout == "1"
  tags: openldap

- name: "Be sure that OpenLDAP is installed with its utilities"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: yes
  notify:
   - "Safe Upgrade"
  with_items:
    - slapd
    - ldap-utils
  tags: openldap

- name: "Be sure that the directory '/var/log/slapd' is present or create it"
  file:
    path: /var/log/slapd
    state: directory
  tags: openldap

- name: "Be sure that logs of OpenLDAP are stored into /var/log/slapd/slapd.log"
  copy:
   src: "files/99-slapd.conf"
   dest: "/etc/rsyslog.d/99-slapd.conf"
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart rsyslogd"
   - "Restart slapd"
  tags: openldap

- name: "Be sure that the OpenLDAP user is added to 'ssl-cert' group"
  user: 
   name: openldap
   groups: ssl-cert
  notify:
   - "Restart slapd"
  tags: openldap

- name: "Be sure that the directory '/root/ldap-configs' is present or create it"
  file:
    path: /root/ldap-configs
    state: directory
    mode: 0600
  tags: openldap

- name: "Be sure that the directory configuration LDIFs are stored into /root/ldap-configs"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "0600"
  with_items:
   - src: "directory-config.ldif.j2"
     dest: "/root/ldap-configs/directory-config.ldif"
  tags: openldap 

- name: "Be sure that eduPerson, schac schema and overlay are stored into /root/ldap-configs"
  copy:
   src: "files/{{ item }}"
   dest: "/root/ldap-configs"
   owner: "root"
   group: "root"
   mode: "0644"
  with_items:
   - eduperson-201602.ldif
   - schac-20150413.ldif
  tags: openldap

- name: "Be sure that 'ldap.conf' is configured correctly"
  copy:
   src: "files/ldap.conf"
   dest: "/etc/ldap/ldap.conf"
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart slapd"
  tags: openldap

- name: "Check if LDAP has alread the olcTLSCertificateKeyFile needed for STARTTLS and store the result on 'olc_cert_key' ansible variable"
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=config '(olcTLSCertificateKeyFile=*)' dn olcTLSCertificateKeyFile"
  register: olc_cert_key
  changed_when: false
  tags: openldap

- name: "Be sure that SLAPD is restarted before applying new ldap configuration"
  service:
    name: "slapd"
    state: "restarted"
  when: olc_cert_key.stdout == ""
  tags: openldap

- name: "Be sure that the Directory is configured correctly"
  command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f /root/ldap-configs/directory-config.ldif"
  when: olc_cert_key.stdout == ""
  notify: 
   - "Restart slapd"
  tags: openldap

- name: "Check eduPerson schema on LDAP and store the result on 'eduperson_schema' ansible variable"
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=schema,cn=config cn=*eduperson dn"
  register: eduperson_schema
  changed_when: false
  tags: openldap

- name: "Be sure that the eduperson-201602 schema is added"
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /root/ldap-configs/eduperson-201602.ldif"
  when: eduperson_schema.stdout == ""
  notify: 
   - "Restart slapd"
  tags: openldap

- name: "Check SCHAC schema on LDAP and store the result on 'schac_schema' ansible variable"
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=schema,cn=config cn=*schac dn"
  register: schac_schema
  changed_when: false
  tags: openldap

- name: "Be sure that the schac-20150413 schema is added"
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /root/ldap-configs/schac-20150413.ldif"
  when: schac_schema.stdout == ""
  notify: 
   - "Restart slapd"
  tags: openldap

- name: "Check Password Policy schema on LDAP and store the result on 'ppolicy_schema' ansible variable"
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=schema,cn=config cn=*ppolicy dn"
  register: ppolicy_schema
  changed_when: false
  tags: openldap 
 
- name: "Be sure that the Password Policy are enabled on OpenLDAP"
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/ppolicy.ldif"
  when: ppolicy_schema.stdout == ""
  notify:
   - "Restart slapd"
  tags: openldap

- include: add_people_groups_system_policies_branches.yml
  notify:
   - "Restart slapd"
  tags: openldap

- include: add_idpuser.yml
  notify:
   - "Restart slapd"
  tags: openldap

- include: add_testuser.yml
  when: 
   - ldap['create_test_user'] is defined
   - ldap['create_test_user'] in ["Yes","yes","True","true"]
  notify: 
   - "Restart slapd"
  tags: openldap

- include: add_memberof_overlay.yml
  notify:
   - "Restart slapd"
  tags: openldap

- include: add_ppolicy_overlay.yml
  notify:
   - "Restart slapd"
  tags: openldap 

- include: add_password_policy_entry.yml
  notify:
   - "Restart slapd"
  tags: openldap

- name: "Be sure to create directory needed for backups"
  file:
   dest: "{{ item }}"
   state: "directory"
   owner: "root"
   group: "root"
   mode: "640"
  with_items:
   - "/var/local/backups"
   - "/var/local/backups/ldap"
  tags: openldap

- name: "Be sure to have ldap backup script in the right position"
  template:
   src: "ldap-backup.sh.j2"
   dest: "/etc/cron.daily/ldap-backup"
   owner: "root"
   group: "root"
   mode: "0755"
  tags: openldap 

- name: "Check if the Directory is not empty"
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b '{{ ldap['basedn'] }}' '(&(|(ou:dn:=people)(ou:dn:=groups))(!(objectClass=organizationalUnit))(!(uid=testuser)))'" 
  register: ldap_is_empty
  changed_when: false
  tags: openldap

- name: "RESTORE - Be sure to put the backup into the /root directory"
  copy:
   src: "files/restore/{{ fqdn }}/ldap-backup/ldap-users.ldif.gz"
   dest: "/root/ldap-users.ldif.gz"
   owner: "root"
   group: "root"
   mode: "0600"
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "RESTORE - Be sure to extract the LDAP Backup into the right position"
  command: "gunzip /root/ldap-users.ldif.gz"
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "RESTORE - Be sure that the ldap-users has the right permission"
  file:
   dest: "/root/ldap-users.ldif"
   owner: "root"
   group: "root"
   mode: "600"
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "RESTORE - Be sure to stop SLAPD before to restore entries"
  service:
   name: slapd
   state: stopped
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "RESTORE - Be sure to restore ldap entries"
  command: "slapadd -c -l /root/ldap-users.ldif"
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "RESTORE - Be sure to remove the ldap-users.ldif restored"
  file:
   dest: "/root/ldap-users.ldif" 
   state: "absent"
  when:
   - ldap['restore'] is defined
   - ldap['restore'] in ["Yes","yes","True","true"]
   - ldap_is_empty.stdout == ""
  tags: openldap

- name: "Be sure that OpenLDAP is up and running"
  service: 
   name: slapd
   state: started
   enabled: yes
  tags: openldap
