---
# tasks file for phpldapadmin
- name: "Be sure that phpLDAPadmin is installed"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: yes
  with_items:
   - apache2-utils
   - python-passlib
   - phpldapadmin
   - gettext
  notify:
   - "Safe Upgrade"
   - "Restart Apache"
  tags: pla

- name: "Be sure to configure phpLDAPadmin correctly"
  template:
   src: config.php.j2
   dest: /etc/phpldapadmin/config.php
   owner: "root"
   group: "www-data"
  notify:
   - "Restart Apache"
  tags: pla

- name: "Be sure to configure 'admin' user for phpLDAPadmin"
  htpasswd:
    path: /etc/apache2/htpasswd
    name: admin
    password: "{{ ldap['root_pw'] }}"
    owner: root
    group: root
    mode: 0644
  tags: pla

- name: "Be sure to change '/phpldapadmin' into '/idm' to prevent random login attempts"
  replace:
   dest: /etc/apache2/conf-enabled/phpldapadmin.conf
   regexp: "Alias /phpldapadmin /usr/share/phpldapadmin/htdocs"
   replace: "Alias /idm /usr/share/phpldapadmin/htdocs"
  notify:
   - "Restart Apache"
  tags: pla

- name: "Be sure to load the configuration files for phpLDAPadmin"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ item.owner }}"
   group: "{{ item.group }}"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/idm.conf", dest: "/etc/apache2/conf-enabled/idm.conf", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/restore/{{ fqdn }}/images/logo.png", dest: "/usr/share/phpldapadmin/htdocs/images/default/logo-small.png", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/jquery-1.9.1.min.js", dest: "/usr/share/phpldapadmin/htdocs/js/jquery-1.9.1.min.js", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/jquery-ui-1.9.1.min.js", dest: "/usr/share/phpldapadmin/htdocs/js/jquery-ui-1.9.1.min.js", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/jquery.min.map", dest: "/usr/share/phpldapadmin/htdocs/js/jquery.min.map", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/livevalidation_standalone.compressed.js", dest: "/usr/share/phpldapadmin/htdocs/js/livevalidation_standalone.compressed.js", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/custom.css", dest: "/usr/share/phpldapadmin/htdocs/css/default/custom.css", owner: "root" , group: "root" , mode: "0644"  }
  notify:
   - "Restart Apache"
  tags: pla

- name: "Be sure to create 'idm-tools' directory"
  file:
   path: "/usr/share/phpldapadmin/htdocs/idm-tools"
   state: directory
   mode: 0755
  tags: pla

- name: "Be sure that all templates are present"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  with_items:
   - { src: "homeJavascript.js.j2", dest: "/usr/share/phpldapadmin/htdocs/js/homeJavascript.js", mode: "0644" }
   - { src: "formJavascript.js.j2", dest: "/usr/share/phpldapadmin/htdocs/js/formJavascript.js", mode: "0644" }
   - { src: "checkValue.php.j2", dest: "/usr/share/phpldapadmin/htdocs/checkValue.php", mode: "0644" }
   - { src: "lockuser.php.j2", dest: "/usr/share/phpldapadmin/htdocs/lockuser.php", mode: "0644" }
   - { src: "lockusers.py.j2", dest: "/etc/cron.daily/lockusers.py", mode: "0755" }
   - { src: "action_lock.php.j2", dest: "/usr/share/phpldapadmin/htdocs/action_lock.php", mode: "0644" }
  # - { src: "messages_it.po.j2", dest: "/usr/share/phpldapadmin/locale/it_IT/LC_MESSAGES/messages_it.po", mode: "0644" }
   - { src: "index.php.j2", dest: "/usr/share/phpldapadmin/htdocs/idm-tools/index.php", mode: "0644" }
  tags: pla

- name: "Be sure to put easy identity template on PLA"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "www-data"
    mode: "{{ item.mode }}"
  with_items:
   - { src: "create_idpAccount_easy.xml.j2", dest: "/etc/phpldapadmin/templates/creation/custom_idpAccount.xml", mode: "0640" }
   - { src: "modify_idpAccount_easy.xml.j2", dest: "/etc/phpldapadmin/templates/modification/custom_idpAccount.xml", mode: "0640" }
  when: 
   - pla['easy_idm'] is defined
   - pla['easy_idm'] in ["Yes","yes","True","true"]
  tags: pla
 
- name: "Be sure to put full identity template on PLA"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "www-data"
    mode: "{{ item.mode }}"
  with_items:
   - { src: "create_idpAccount.xml.j2", dest: "/etc/phpldapadmin/templates/creation/custom_idpAccount.xml", mode: "0640" }
   - { src: "modify_idpAccount.xml.j2", dest: "/etc/phpldapadmin/templates/modification/custom_idpAccount.xml", mode: "0640" }
  when: 
   - pla['easy_idm'] is not defined or pla['easy_idm'] in ["No","no","False","false"]
  tags: pla

#- name: "Be sure to create italian messages for PLA"
#  command: "/usr/bin/msgfmt messages.po" 
#  args:
#    chdir: "/usr/share/phpldapadmin/locale/it_IT/LC_MESSAGES" 
#  changed_when: false
#  tags: pla

- name: "Check if TemplateRenderOrig.php exists"
  stat: 
   path: "/usr/share/phpldapadmin/lib/TemplateRenderOrig.php"
  register: templRendOrig
  tags: pla

- name: "Change TemplateRender.php"
  replace:
   dest: "/usr/share/phpldapadmin/lib/TemplateRender.php"
   regexp: "class TemplateRender extends PageRender"
   replace: "class TemplateRenderOrig extends PageRender"
  when: not templRendOrig['stat']['exists']
  tags: pla

#- name: "Change TemplateRender.php"
#  command: "/bin/sed -i -e's/class TemplateRender extends PageRender/class TemplateRenderOrig extends PageRender/' TemplateRender.php"
#  args:
#   chdir: "/usr/share/phpldapadmin/lib/"
#  when: tempRendOrig.stat is not defined
#  tags: pla

- name: "Rename TemplateRender.php into TemplateRenderOrig.php"
  command: "mv TemplateRender.php TemplateRenderOrig.php"
  args:
   chdir: "/usr/share/phpldapadmin/lib/"
  when: not templRendOrig['stat']['exists']
  tags: pla

- name: "Be sure to create new TemplateRender.php"
  copy:
   src: "files/TemplateRender.php"
   dest: "/usr/share/phpldapadmin/lib/TemplateRender.php"
   owner: "root"
   group: "root"
   mode: "0644"
  when: not templRendOrig['stat']['exists']
  notify:
   - "Restart Apache"
  tags: pla

- name: "Check if TemplateOrig.php exists"
  stat: 
   path: "/usr/share/phpldapadmin/lib/TemplateOrig.php"
  register: templOrig
  tags: pla

- name: "Change Template.php"
  replace:
   dest: "/usr/share/phpldapadmin/lib/Template.php"
   regexp: "class Template extends xmlTemplate"
   replace: "class TemplateOrig extends xmlTemplate"
  when: not templOrig['stat']['exists']
  tags: pla

#- name: "Change Template.php"
#  command: "/bin/sed -i -e's/class Template extends xmlTemplate/class TemplateOrig extends xmlTemplate/' Template.php"
#  args:
#   chdir: "/usr/share/phpldapadmin/lib/"
#  when: tempOrig.stat is not defined
#  tags: pla

- name: "Rename Template.php into TemplateOrig.php"
  command: "mv Template.php TemplateOrig.php"
  args:
    chdir: "/usr/share/phpldapadmin/lib/"
  when: not templOrig['stat']['exists']
  tags: pla

- name: "Be sure to create new Template.php"
  copy:
   src: "files/Template.php"
   dest: "/usr/share/phpldapadmin/lib/Template.php"
   owner: "root"
   group: "root"
   mode: "0644"
  when: not templOrig['stat']['exists']
  notify:
   - "Restart Apache"
  tags: pla

- name: "Check if pageOrig.php exists"
  stat: 
   path: "/usr/share/phpldapadmin/lib/pageOrig.php"
  register: pageOrig
  tags: pla

- name: "Change page.php"
  replace:
   dest: "/usr/share/phpldapadmin/lib/page.php"
   regexp: "class page"
   replace: "class pageOrig"
  when: not pageOrig['stat']['exists']
  tags: pla

#- name: "Change page.php"
#  command: "/bin/sed -i -e's/class page/class pageOrig/' page.php"
#  args:
#   chdir: "/usr/share/phpldapadmin/lib/"
#  when: pageOrig.stat is not defined
#  tags: pla

- name: "Rename page.php into pageOrig.php"
  command: "mv page.php pageOrig.php"
  args:
    chdir: "/usr/share/phpldapadmin/lib/"
  when: not pageOrig['stat']['exists']
  tags: pla

- name: "Be sure to create new page.php"
  copy:
   src: "files/page.php"
   dest: "/usr/share/phpldapadmin/lib/page.php"
   owner: "root"
   group: "root"
   mode: "0644"
  when: not pageOrig['stat']['exists']
  notify:
   - "Restart Apache"
  tags: pla

- name: "Check if create.php needs changes"
  shell: "/bin/grep -F 'default' create.php | wc -l"
  args:
    chdir: "/usr/share/phpldapadmin/htdocs/"
  register: create_mod
  changed_when: false
  tags: pla

- name: "Change create.php"
  replace:
   dest: "/usr/share/phpldapadmin/htdocs/create.php"
   regexp: "default"
   replace: "custom_idpAccount:0"
  when: create_mod['stdout'] != "0"
  tags: pla

#- name: "Change create.php"
#  command: "/bin/sed -i -e 's/default/custom_idpAccount:0/' create.php"
#  args:
#    chdir: "/usr/share/phpldapadmin/htdocs/"
#  when: create_mod.stdout != "0"
#  tags: pla

- name: "Check if HTMLTree needs changes"
  shell: "/bin/grep -F 'return pretty_print_dn($entry->getDN());' HTMLTree.php | wc -l"
  args:
    chdir: "/usr/share/phpldapadmin/lib/"
  register: htmltree_mod
  changed_when: false
  tags: pla

- name: "Change HTMLTree.php"
  replace:
   dest: "/usr/share/phpldapadmin/lib/HTMLTree.php"
   regexp: "return pretty_print_dn[(][$]entry->getDN[(][)][)];"
   replace: "return \"Users\";"
  when: htmltree_mod['stdout'] != "0"
  tags: pla

#- name: "Change HTMLTree.php"
#  command: /bin/sed -i -e 's/return pretty_print_dn(\$entry->getDN());/return \"Users\";/' HTMLTree.php
#  args:
#    chdir: "/usr/share/phpldapadmin/lib/"
#  when: htmltree_mod.stdout != "0"
#  tags: pla

