---
# tasks file for apache
- name: "Be sure that apache2 user is added to ssl-cert group"
  user:
   name: "apache2"
   groups: "ssl-cert"

- name: "Be sure to have SSL, include, negotiation, headers and Proxy modules enabled"
  apache2_module:
   name: "{{ item }}"
   state: present
  with_items:
   - alias
   - ssl
   - include
   - negotiation
   - headers
   - proxy_http
  notify:
   - "Restart Apache"

- name: "Be sure to have Apache SSL site configured correctly"
  template:
   src: default-ssl.conf.j2
   dest: /etc/apache2/sites-enabled/default-ssl.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Be sure to have Apache HTTP site has the redirection to HTTPS"
  template:
   src: default.conf.j2
   dest: /etc/apache2/sites-enabled/000-default.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Be sure to have enabled Apache localized error pages"
  copy:
   src: files/localized-error-pages.conf
   dest: /etc/apache2/conf-enabled/localized-error-pages.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"
