- name: "Run 'apt-get update' if the last one is more than 3600 seconds ago"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install debian packages for python application"
  apt:
    name: ['python-dev', 'python-setuptools', 'python-mysqldb', 'default-libmysqlclient-dev', 'sqlite3', 'libxml2-dev', 'libxslt-dev', 'libldap2-dev', 'libsasl2-dev', 'git', 'build-essential', 'apache2', 'libapache2-mod-wsgi','python-pip']
    state: latest

- name: "Install virtualenv"
  pip:
    name: virtualenv

