---
# file: shib-idp-servers.yml
- hosts: Debian-IdP-without-IdM-GARR
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
#    - common
#    - apache
#    - jdk
#    - jetty
#    - mysql
#    - idp
#    - check_mk_agent
    - rsync-backup-user
#    - sys-update
  serial: 3
