---
# file: shib-idp-ldap-servers.yml
- hosts: Debian
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
    - common
    - apache
    - jetty
    - openldap
    - mysql
    - idp
    - phpldapadmin
