---
# file: site.yml
- import_playbook: shib-idp-servers.yml
- import_playbook: shib-idp-idm-servers.yml
- import_playbook: shib-idp-servers-garr.yml
- import_playbook: shib-idp-idm-servers-garr.yml
- import_playbook: enable_maintenance.yml
- import_playbook: disable_maintenance.yml
- import_playbook: backup.yml
