---
# handlers file for openldap
- name: "Restart slapd"
  become: yes
  become_method: sudo
  service:
   name: slapd
   state: restarted

- name: "Restart rsyslogd"
  become: yes
  become_method: sudo
  service:
   name: rsyslog
   state: restarted
