idp_attrDef:
   uid:
      AttributeDefinition:
         id: "uid"
         type: "Simple"
         sourceAttributeID: "uid"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "UserID"
         it: "UserID"
      DisplayDescription:
         en: "User Identifier"
         it: "Identificativo di questo utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:0.9.2342.19200300.100.1.1"
            friendlyName: "uid"
            encodeType: "false"
   surname:
      AttributeDefinition:
         id: "surname"
         type: "Simple"
         sourceAttributeID: "sn"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Surname"
         it: "Cognome"
      DisplayDescription:
         en: "Surname of user"
         it: "Cognome utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.5.4.4"
            friendlyName: "sn"
            encodeType: "false"
   givenName:
      AttributeDefinition:
         id: "giveName"
         type: "Simple"
         sourceAttributeID: "givenName"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Nome"
         it: "Nome"
      DisplayDescription:
         en: "Given name of a person"
         it: "Nome proprio di una persona"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.5.4.42"
            friendlyName: "givenName"
            encodeType: "false"
   commonName:
      AttributeDefinition:
         id: "commonName"
         type: "Simple"
         sourceAttributeID: "cn"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "CommonName"
         it: "Nome e Cognome"
      DisplayDescription:
         en: "One or more names that should appear in white-pages-like applications of this person"
         it: "Nome e Cognome proprio di una persona"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.5.4.3"
            friendlyName: "cn"
            encodeType: "false"
   title:
      AttributeDefinition:
         id: "title"
         type: "Simple"
         sourceAttributeID: "title"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Title"
         it: "Titolo"
      DisplayDescription:
         en: "Title inside the institution"
         it: "Titolo della persona nel contesto dell'istituzione"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.5.4.12"
            friendlyName: "title"
            encodeType: "false"
   email:
      AttributeDefinition:
         id: "email"
         type: "Simple"
         sourceAttributeID: "mail"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "E-mail"
         it: "E-mail"
      DisplayDescription:
         en: "E-mail: Preferred address for email to be sent to this person"
         it: "E-mail: Indirizzo e-mail preferito dall'utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:0.9.2342.19200300.100.1.3"
            friendlyName: "mail"
            encodeType: "false"
   telephoneNumber:
      AttributeDefinition:
         id: "telephoneNumber"
         type: "Simple"
         sourceAttributeID: "telephoneNumber"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Telephone Number"
         it: "Numero di Telefono"
      DisplayDescription:
         en: "Telephone Number"
         it: "Numero di Telefono"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.5.4.20"
            friendlyName: "telephoneNumber"
            encodeType: "false"
   mobile:
      AttributeDefinition:
         id: "mobile"
         type: "Simple"
         sourceAttributeID: "mobile"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Mobile Telephone Number"
         it: "Numero di Telefono Mobile"
      DisplayDescription:
         en: "Mobile Telephone Number"
         it: "Numero di Telefono Mobile"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:0.9.2342.19200300.100.1.41"
            friendlyName: "mobile"
            encodeType: "false"
   facsimileTelephoneNumber:
      AttributeDefinition:
         id: "facsimileTelephoneNumber"
         type: "Simple"
         sourceAttributeID: "facsimileTelephoneNumber"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Facsimile Numbe"
         it: "Numero del FAX"
      DisplayDescription:
         en: "Facsimile Numbe"
         it: "Numero del FAX"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.1466.115.121.1.22"
            friendlyName: "facsimileTelephoneNumber"
            encodeType: "false"
   displayName:
      AttributeDefinition:
         id: "displayName"
         type: "Simple"
         sourceAttributeID: "displayName"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Display name"
         it: "Nome visualizzato"
      DisplayDescription:
         en: "Preferred name of a person to be used when displaying entries"
         it: "Nome che una persona preferisce visualizzare"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.16.840.1.113730.3.1.241"
            friendlyName: "displayName"
            encodeType: "false"
   preferredLanguage:
      AttributeDefinition:
         id: "preferredLanguage"
         type: "Simple"
         sourceAttributeID: "preferredLanguage"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Preferred Language"
         it: "Lingua Preferita"
      DisplayDescription:
         en: "Preferred Language of the user"
         it: "Lingua Preferita dall'utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:2.16.840.1.113730.3.1.39"
            friendlyName: "preferredLanguage"
            encodeType: "false"
   eduPersonOrgDN:
      AttributeDefinition:
         id: "eduPersonOrgDN"
         type: "Simple"
         sourceAttributeID: "eduPersonOrgDN"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "eduPersonOrgDN"
         it: "eduPersonOrgDN"
      DisplayDescription:
         en: "Organization path: The distinguished name (DN) of the directory entry representing the organization with which the person is associated"
         it: "DN dell'organizzazione: Il DN dell'organizzazione a cui è associato questo utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.3"
            friendlyName: "eduPersonOrgDN"
            encodeType: "false"
   eduPersonOrgUnitDN:
      AttributeDefinition:
         id: "eduPersonOrgUnitDN"
         type: "Simple"
         sourceAttributeID: "eduPersonOrgUnitDN"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "eduPersonOrgUnitDN"
         it: "eduPersonOrgUnitDN"
      DisplayDescription:
         en: "Organization unit path: The distinguished name (DN) of the directory entries representing the person's Organizational Unit(s)"
         it: "DN dell'unità: Il DN dell'unità organizzativa di questo utente nella sua organizzazione"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.4"
            friendlyName: "eduPersonOrgUnitDN"
            encodeType: "false"
   eduPersonAffiliation:
      AttributeDefinition:
         id: "eduPersonAffiliation"
         type: "Simple"
         sourceAttributeID: "eduPersonAffiliation"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Affiliation"
         it: "Affiliazione"
      DisplayDescription:
         en: "Affiliation: Type of affiliation with Home Organization"
         it: "Affiliazione: Tipo di relazione mantenuta con la propria organizzazione"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.1"
            friendlyName: "eduPersonAffiliation"
            encodeType: "false"
   eduPersonScopedAffiliation:
      AttributeDefinition:
         id: "eduPersonScopedAffiliation"
         type: "Scoped"
         sourceAttributeID: "eduPersonScopedAffiliation"
         scope: "%{idp.scope}"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Scoped Affiliation"
         it: "Affiliazione con ambito"
      DisplayDescription:
         en: "Affiliation Scoped: Type of affiliation with Home Organization with scope"
         it: "Affiliazione con ambito: ruolo ricoperto con dominio dell'Organizzazione"
      AttributeEncoder:
         SAML2ScopedString:
            type: "SAML2ScopedString"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.9"
            friendlyName: "eduPersonScopedAffiliation"
            encodeType: "false"
   eduPersonPrincipalName:
      AttributeDefinition:
         id: "eduPersonPrincipalName"
         type: "Scoped"
         sourceAttributeID: "uid"
         scope: "%{idp.scope}"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "eduPersonPrincipalName"
         it: "eduPersonPrincipalName"
      DisplayDescription:
         en: "Unique and persistent Identifier of a person"
         it: "Identificativo unico persistente di questo utente"
      AttributeEncoder:
         SAML2ScopedString:
            type: "SAML2ScopedString"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
            friendlyName: "eduPersonPrincipalName"
            encodeType: "false"
   eduPersonEntitlement:
      AttributeDefinition:
         id: "eduPersonEntitlement"
         type: "Simple"
         sourceAttributeID: "eduPersonEntitlement"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Entitlement"
         it: "Entitlement"
      DisplayDescription:
         en: "Entitlement: URI (either URL or URN) that indicates a set of rights to specific resources based on an agreement across the releavant community"
         it: "Entitlement: URI (sia URL o URN) che rappresenta diritti specifici d'accesso validi in tutta la community"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.7"
            friendlyName: "eduPersonEntitlement"
            encodeType: "false"
   eduPersonTargetedID:
      AttributeDefinition:
         id: "eduPersonTargetedID"
         type: "SAML2NameID"
         nameIdFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
         sourceAttributeID: "persistentID"
      Dependency:
         eef_dc_ldap: "myStoredId"
      DisplayName:
         en: "Opaque per-service identifier eduPersonTargetedID"
         it: "Identificatore opaco diverso per ogni servizio eduPersonTargetedID"
      DisplayDescription:
         en: "Opaque per-service identifier eduPersonTargetedID"
         it: "Identificatore opaco diverso per ogni servizio eduPersonTargetedID"
      AttributeEncoder:
         SAML2XMLObject:
            type: "SAML2XMLObject"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.10"
            friendlyName: "eduPersonTargetedID"
            encodeType: "false"
   eduPersonOrcid:
      AttributeDefinition:
         id: "eduPersonOrcid"
         type: "Simple"
         sourceAttributeID: "eduPersonOrcid"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "ORCID"
         it: "ORCID"
      DisplayDescription:
         en: "ORCID user identifier released and managed by orcid.org"
         it: "Identificativi ricercatore ORCID dell’utente assegnati e gestiti da orcid.org"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.16"
            friendlyName: "eduPersonOrcid"
            encodeType: "false"
   schacMotherTongue:
      AttributeDefinition:
         id: "schacMotherTongue"
         type: "Simple"
         sourceAttributeID: "schacMotherTongue"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Mother Tongue"
         it: "Lingua Madre"
      DisplayDescription:
         en: "Mother Tongue of the user"
         it: "Lingua Madre dell'utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.1"
            friendlyName: "schacMotherTongue"
            encodeType: "false"
   schacPersonalTitle:
      AttributeDefinition:
         id: "schacPersonalTitle"
         type: "Simple"
         sourceAttributeID: "schacPersonalTitle"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Personal Title"
         it: "Soprannome"
      DisplayDescription:
         en: "Nice name used for the user"
         it: "Titolo usato per salutare l'utente"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.8"
            friendlyName: "schacPersonalTitle"
            encodeType: "false"
   schacPersonalPosition:
      AttributeDefinition:
         id: "schacPersonalPosition"
         type: "Simple"
         sourceAttributeID: "schacPersonalPosition"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Personal Position"
         it: "Ruolo ricoperto"
      DisplayDescription:
         en: "Personal Position of the user for the institution"
         it: "Ruolo dell'utente nell'istituzione"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.13"
            friendlyName: "schacPersonalPosition"
            encodeType: "false"
   schacUserPresenceID:
      AttributeDefinition:
         id: "schacUserPresenceID"
         type: "Simple"
         sourceAttributeID: "schacUserPresenceID"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "User Network IDs"
         it: "Il nome a dominio dell’organizzazione di appartenenza dell’utente"
      DisplayDescription:
         en: "Identifiers that user collect on the net"
         it: "Identificativi usati dall'utente sulla rete"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.12"
            friendlyName: "schacUserPresenceID"
            encodeType: "false"
   schacHomeOrganization:
      AttributeDefinition:
         id: "schacHomeOrganization"
         type: "ScriptedAttribute"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Institution Domain"
         it: "Dominio Istituzione"
      DisplayDescription:
         en: "Domain of the institution"
         it: "Dominio dell'istituzione"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.9"
            friendlyName: "schacHomeOrganization"
            encodeType: "false"
      Script: |
              <![CDATA[
               importPackage (Packages.org.slf4j);
               logger = LoggerFactory.getLogger("net.shibboleth.idp.attribute");

               // This implementation composes the value of the attribute schacHomeOrganization
               // from the values of the properties idp.scope inside idp.properties.

               if (typeof schacHomeOrganization === 'undefined' || schacHomeOrganization.getValues().size() < 1) {

               logger.info("No schacHomeOrganization in LDAP found, creating one");

               // compose value from 'schacHomeOrganization'
               schacHomeOrganization.addValue("%{idp.scope}");
               logger.info("schacHomeOrganization final value: " + schacHomeOrganization.getValues().get(0));

               } else {
               logger.info("schacHomeOrganization has value: " + schacHomeOrganization.getValues().get(0));
               }
              ]]>
   schacHomeOrganizationType:
      AttributeDefinition:
         id: "schacHomeOrganizationType"
         type: "Simple"
         sourceAttributeID: "schacHomeOrganizationType"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Home organization type (international)"
         it: "Tipo dell'organizzazione di appartenenza (internazionale)"
      DisplayDescription:
         en: "Home Organization Type: Type of a Home Organization"
         it: "Tipo dell'organizzazione di appartenenza"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.10"
            friendlyName: "schacHomeOrganizationType"
            encodeType: "false"
   schacPersonalUniqueID:
      AttributeDefinition:
         id: "schacPersonalUniqueID"
         type: "Simple"
         sourceAttributeID: "schacPersonalUniqueID"
      Dependency:
         ref_dc_ldap: "myLDAP"
      DisplayName:
         en: "Legal Unique ID"
         it: "ID Legale Univoco"
      DisplayDescription:
         en: "Unique Legal Identifier of a person"
         it: "Identificativo Univoco Legale associato alla persona"
      AttributeEncoder:
         SAML2String:
            type: "SAML2String"
            name: "urn:oid:1.3.6.1.4.1.25178.1.2.15"
            friendlyName: "schacPersonalUniqueID"
            encodeType: "false"
