---
# tasks file for idm-configure

- name: "Check if pageOrig exists"
  stat:
   path: "/opt/phpldapadmin/lib/pageOrig.php"
  register: pageOrig

- name: "Check if TemplateRenderOrig exists"
  stat:
   path: "/opt/phpldapadmin/lib/TemplateRenderOrig.php"
  register: TemplateRenderOrig

- name: "Be sure to patch phpLDAPadmin page.php file"
  patch:
   src: "files/phpldapadmin/lib/page.php.patch"
   dest: "/opt/phpldapadmin/lib/page.php"
  when: pageOrig.stat.exists == false

- name: "Be sure to patch phpLDAPadmin TemplateRender.php file"
  patch:
   src: "files/phpldapadmin/lib/TemplateRender.php.patch"
   dest: "/opt/phpldapadmin/lib/TemplateRender.php"
  when: TemplateRenderOrig.stat.exists == false

- name: "Rename page to pageOrig"
  command: "mv /opt/phpldapadmin/lib/page.php /opt/phpldapadmin/lib/pageOrig.php"
  when: pageOrig.stat.exists == false

- name: "Rename TemplateRender to TemplateRenderOrig"
  command: "mv /opt/phpldapadmin/lib/TemplateRender.php /opt/phpldapadmin/lib/TemplateRenderOrig.php"
  when: TemplateRenderOrig.stat.exists == false

- name: "Be sure to copy the new page.php"
  copy:
   src: "files/phpldapadmin/lib/page.php"
   dest: "/opt/phpldapadmin/lib/page.php"
   owner: "root"
   group: "root"
   mode: "0644"
  changed_when: False

- name: "Be sure to copy the new TemplateRender.php"
  copy:
   src: "files/phpldapadmin/lib/TemplateRender.php"
   dest: "/opt/phpldapadmin/lib/TemplateRender.php"
   owner: "root"
   group: "root"
   mode: "0644"
  changed_when: False

- name: "Be sure to copy needed PLA changed javascripts"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/phpldapadmin/htdocs/js/homeJavascript.js", dest: "/opt/phpldapadmin/htdocs/js/homeJavascript.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/formJavascript.js", dest: "/opt/phpldapadmin/htdocs/js/formJavascript.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery-1.9.1.min.js", dest: "/opt/phpldapadmin/htdocs/js/jquery-1.9.1.min.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery.min.map", dest: "/opt/phpldapadmin/htdocs/js/jquery.min.map", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery-ui-1.9.1.min.js", dest: "/opt/phpldapadmin/htdocs/js/jquery-ui-1.9.1.min.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/livevalidation_standalone.compressed.js", dest: "/opt/phpldapadmin/htdocs/js/livevalidation_standalone.compressed.js", mode: "0644" }

- name: "Be sure to patch phpLDAPadmin 'create.php' file"
  patch:
   src: "files/phpldapadmin/htdocs/create-idpcloud.patch"
   dest: "/opt/phpldapadmin/htdocs/create.php"
  changed_when: False

- name: "Be sure to copy 'checkValue.php' on phpldapadmin/htdocs"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/htdocs/checkValue.php.j2", dest: "/opt/phpldapadmin/htdocs/checkValue.php", mode: "0644" }

- name: "Be sure to add needed files for locking/unlocking users"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/htdocs/lockuser.php.j2", dest: "/opt/phpldapadmin/htdocs/lockuser.php", mode: "0644" }
   - { src: "lockusers.py.j2", dest: "/etc/cron.hourly/lockusers", mode: "0755" }
   - { src: "phpldapadmin/htdocs/action_lock.php.j2", dest: "/opt/phpldapadmin/htdocs/action_lock.php", mode: "0644" }

- name: "Be sure to update configuration of phpLDAPadmin"
  template:
   src: "phpldapadmin/config/config.php.j2"
   dest: "/opt/phpldapadmin/config/config.php"
   owner: "root"
   group: "www-data"
  changed_when: False

- name: "Check if the template used to create user is provided"
  stat:
   path: "/opt/phpldapadmin/lib/TemplateRenderOrig.php"
  register: TemplateRenderOrig

# Load /opt/phpldapadmin/templates/creation/custom_idpAccount.xml
- name: "Check if 'creation/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml' is provided under {{ files_dir }}/<FQDN>/idpcloud_garr/phpldapadmin/templates"
  stat:
   path: "{{ files_dir }}/{{ fqdn }}/idpcloud_garr/phpldapadmin/templates/creation/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml"
  delegate_to: 127.0.0.1
  register: customPLAcreationTemplate
  changed_when: false

- name: "Load custom 'creation/custom_idpAccount.xml' provided"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/idpcloud_garr/phpldapadmin/templates/creation/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml"
   dest: "/opt/phpldapadmin/templates/creation/custom_idpAccount.xml"
   owner: "root"
   group: "www-data"
   mode: "0640"
  when:
   - customPLAcreationTemplate.stat.exists == True
  notify:
   - "Restart Apache"

# Load /opt/phpldapadmin/templates/modification/custom_idpAccount.xml
- name: "Check if 'modification/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml' is provided under {{ files_dir }}/<FQDN>/idpcloud_garr/phpldapadmin/templates"
  stat:
   path: "{{ files_dir }}/{{ fqdn }}/idpcloud_garr/phpldapadmin/templates/modification/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml"
  delegate_to: 127.0.0.1
  register: customPLAmodificationTemplate
  changed_when: false

- name: "Load custom 'modification/custom_idpAccount.xml' provided"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/idpcloud_garr/phpldapadmin/templates/modification/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml"
   dest: "/opt/phpldapadmin/templates/modification/custom_idpAccount.xml"
   owner: "root"
   group: "www-data"
   mode: "0640"
  when:
   - customPLAmodificationTemplate.stat.exists == True
  notify:
   - "Restart Apache"

- name: "Be sure to add creation/modification PLA templates"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "www-data"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/templates/creation/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml.j2", dest: "/opt/phpldapadmin/templates/creation/custom_idpAccount.xml", mode: "0640" }
   - { src: "phpldapadmin/templates/modification/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml.j2", dest: "/opt/phpldapadmin/templates/modification/custom_idpAccount.xml", mode: "0640" }
  when:
   - customPLAmodificationTemplate.stat.exists == False
  notify:
   - "Restart Apache"
 
- name: "Be sure to enrich phpLDAPadmin with IdP-in-the-Cloud italian templates translation"
  copy:
   src: "files/phpldapadmin/locale/it_IT/LC_MESSAGES/messages-it_{{ idpcloud_garr['idm'] }}.mo"
   dest: "/opt/phpldapadmin/locale/it_IT/LC_MESSAGES/messages.mo"
   owner: "root"
   group: "root"
   mode: "0644"
  changed_when: False

- name: "Be sure to create 'idm-tools' directory"
  file:
   path: "/opt/phpldapadmin/htdocs/idm-tools"
   state: directory
   mode: 0755

- name: "Be sure to load idm-tools index page"
  template:
   src: "phpldapadmin/htdocs/idm-tools/index.php.j2"
   dest: "/opt/phpldapadmin/htdocs/idm-tools/index.php"
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Be sure to load custom CSS for IdP-in-the-Cloud italian templates"
  copy:
   src: "files/phpldapadmin/htdocs/css/default/custom.css"
   dest: "/opt/phpldapadmin/htdocs/css/default/custom.css"
   owner: "root"
   group: "root"
   mode: "0644"

- name: "Check if Apache IDM-TOOLS conf is already enabled"
  stat:
   path: "/etc/apache2/conf-available/idm-tools.conf"
  register: idm_tools_apache
  changed_when: false

- name: "Load Apache IDM-TOOLS conf"
  copy:
   src: "files/apache2/conf-available/idm-tools.conf"
   dest: "/etc/apache2/conf-available/idm-tools.conf"
   owner: "root"
   group: "root"
   mode: "0644"
  when: idm_tools_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"

- name: "Add IDM-TOOLS support to Apache HTTPS VirtualHost"
  blockinfile:
    path: "/etc/apache2/sites-available/{{ fqdn }}-ssl.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - IDM-TOOLS"
    insertbefore: "</VirtualHost>"
    block: |
      Include conf-available/idm-tools.conf
  when: idm_tools_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"

- name: "Be sure to have 'updates.txt' file for users' updates"
  lineinfile:
   dest: "/var/local/backups/updates.txt"
   line: "{{ item.line }}"
   create: "yes"
   state: present
  with_items:
   - { line: "# Data: " }
   - { line: "" }
   - { line: "Nuovi utenti per {{ ldap['org'] }}:" }

- name: "Check if 'updates.txt' file is missing"
  stat:
   path: "/opt/phpldapadmin/htdocs/idm-tools/updates.txt"
  register: updates_txt

- name: "Be sure to create an Hard Link of 'updates.txt' under phpldapadmin dir if missing"
  file:
   src: "/var/local/backups/updates.txt"
   dest: "/opt/phpldapadmin/htdocs/idm-tools/updates.txt"
   state: hard
  when: updates_txt.stat.exists == False

- name: "Be sure to add the Test User - INDIRE IdP"
  ldap_attr:
   dn: "uid=testuser,ou=people,{{ ldap['basedn'] }}"
   name: "schacHomeOrganization"
   values: "{{ idp_config['scope'] }}"
   state: present
  when: ansible_fqdn in ['eduid-pilot.aai.garr.it','eduid-indire.aai.garr.it']
