---
# tasks file for idp-statistics

- name: "Check if Apache STATISTICS conf is already enabled"
  stat:
   path: "/etc/apache2/conf-enabled/statistics.conf"
  register: stats_apache
  changed_when: false

#- name: "Remove any 'statistics.conf' file into '/etc/apache2/conf-enabled'"
#  file:
#   path: "/etc/apache2/conf-enabled/statistics.conf"
#   state: absent
#  when: stats_apache.stat.isreg is defined and stats_apache.stat.isreg
#  notify:
#   - "Restart Apache"

- name: "Load Apache STATISTICS conf"
  copy:
   src: "files/apache2/conf-available/statistics.conf"
   dest: "/etc/apache2/conf-available/statistics.conf"
   owner: "root"
   group: "root"
   mode: "0644"
  when: stats_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"

- name: "Add STATISTICS support to Apache HTTPS VirtualHost"
  blockinfile:
    path: "/etc/apache2/sites-available/{{ fqdn }}-ssl.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - STATISTICS"
    insertbefore: "</VirtualHost>"
    block: |
      Include conf-available/statistics.conf
  when: stats_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"
