---
# tasks file for idp-stats - tag: idpstats

- name: "Load the statistics2csv.sh script into IdP VM"
  ansible.builtin.copy:
   src: "files/idpcloud-scripts/statistics2csv.sh"
   dest: "/tmp/statistics2csv.sh"

- name: "Run statistics2csv.sh script to generate stats files"
  ansible.builtin.command: "bash /tmp/statistics2csv.sh"

- name: "Store files into /tmp/idpstats dir on the vagrant VM"
  ansible.builtin.fetch:
   src: "/tmp/{{ inventory_hostname }}-stats.csv"
   dest: "/tmp/idpstats/"
   flat: yes

- name: "Cleanup"
  ansible.builtin.file:
   path: "{{ item }}"
   state: absent
  loop:
   - "/tmp/{{ inventory_hostname }}-stats.csv"
   - "/tmp/statistics2csv.sh"
