---
# tasks file for idpcloud_garr

- name: "Configure IdM of IdP-in-the-Cloud"
  import_tasks: "idm-configure.yml"
  tags: idpcloud_garr

- name: "Add 'rsync-backup' user needed by rsnapshot server"
  import_tasks: "rsync-backup-configure.yml"
  when: (idpcloud_garr['rsync_backup_ssh_pub_key'] is defined) and (idpcloud_garr['rsync_backup_ssh_pub_key']|length > 0)
  tags: idpcloud_garr
