---
# tasks file for idp
- name: "Check if Shibboleth IdP directory exists and store the result into 'shib_idp_dir' ansible variable"
  stat:
    path: "/opt/shibboleth-idp"
  register: shib_idp_dir

- name: "Be sure that the Shibboleth Identity Provider is downloaded and extracted into the right position"
  become: yes
  become_method: sudo
  unarchive:
    src: "https://shibboleth.net/downloads/identity-provider/{{ shib_idp_version }}/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
    dest: /usr/local/src
    owner: "root"
    group: "root"
    remote_src: True
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that the Shibboleth Identity Provider installer properties' files exists in the right position"
  become: yes
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  with_items:
   - { src: "shib-idp-install.properties.j2", dest: "/tmp/shib-idp-install.properties", mode: "0644" }
   - { src: "installer.properties.j2", dest: "/tmp/installer.properties", mode: "0644" } 
   - { src: "shib-idp-persistentId-db.sql.j2", dest: "/root/shib-idp-persistentId-db.sql", mode: "0600" }
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that Apache2 and Jetty are enabled for Shibboleth IdP"
  become: yes
  become_method: sudo
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: 0644
  with_items:
   - { src: "files/jstl-1.2.jar", dest: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/webapp/WEB-INF/lib/jstl-1.2.jar" }
   - { src: "files/idp.conf", dest: "/etc/apache2/sites-enabled/idp.conf" }
   - { src: "files/idp.xml", dest: "/opt/jetty/webapps/idp.xml" }
  tags: idp 

- name: "Be sure to install Shibboleth IdP"
  become: yes
  become_method: sudo
  shell: "./install.sh -Didp.property.file=/tmp/installer.properties"
  args:
    chdir: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/bin"
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64/jre"
  notify:
    - "Restart Jetty"
    - "Restart Apache"
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that the IdP directories have the right permissions"
  become: yes
  become_method: sudo
  file:
    path: "/opt/shibboleth-idp/{{ item }}"
    owner: "jetty"
    recurse: "yes"
    state: directory
  with_items:
    - logs
    - metadata
    - credentials
    - conf
    - system
    - war
  tags: idp

- name: "Be sure to create the database needed for persistent identifiers"
  become: yes
  become_method: sudo
  mysql_db:
    state: import
    name: all
    target: /root/shib-idp-persistentId-db.sql
  tags: idp
