---
# tasks file for idp
- name: "Be sure that the Shibboleth IdP's directory exists"
  become: yes
  become_method: sudo
  file:
   path: "{{ item }}"
   owner: "root"
   group: "root"
   state: directory
  with_items:
   - /usr/local/src
  tags: idp 

- name: "Be sure that the Shibboleth Identity Provider is downloaded and extracted into the right position"
  become: yes
  become_method: sudo
  unarchive:
    src: "https://shibboleth.net/downloads/identity-provider/{{ shib_idp_version }}/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
    dest: /usr/local/src
    owner: "root"
    group: "root"
    remote_src: True
  tags: idp

- name: "Install Shibboleth Idp"
  become: yes
  become_method: sudo
  command: |
    /usr/local/src/shibboleth-identity-provider-{{ shib_idp_version | quote }}/bin/install.sh \
    -Didp.sealer.password={{ idp_pw | quote }} \
    -Didp.keystore.password={{ idp_pw | quote }} \
    -Didp.scope={{ https_domain | quote }} \
    -Didp.src.dir=/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version | quote }} \
    -Didp.host.name={{ ansible_hostname | quote }} \
    -Didp.target.dir=/opt/shibboleth-idp \
    -Didp.merge.properties=/tmp/shib-install.properties
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64/jre"
  tags: idp

#- name: "Be sure that the JSTL library for IDP Status Page is in the right position"
#  become: yes
#  become_method: sudo
#  copy:
#   src: "{{ item.src }}"
#   dest: "{{ item.dest }}"
#   owner: "{{ item.owner }}"
#   group: "{{ item.group }}"
#   mode: "{{ item.mode }}"
#  with_items:
#   - { src: "files/jstl-1.2.jar", dest: "/opt/shibboleth-idp/edit-webapp/WEB-INF/lib/jstl-1.2.jar", owner: "root" , group: "root" , mode: "0644"  }
#  tags: idp 

- name: "Be sure that the IdP directories have the right permissions"
  become: yes
  become_method: sudo
  file:
    path: "/opt/shibboleth-idp/{{ item }}"
    owner: "jetty"
    recurse: "yes"
    state: directory
  with_items:
    - logs
    - metadata
    - credentials
    - conf
    - system
    - war

