---
# tasks file for idp
- name: "Be sure that Jetty has the right libraries imported"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/share/java/commons-dbcp.jar' , dest: '/opt/jetty/lib/ext/common-dbcp.jar' }
   - { src: '/usr/share/java/commons-pool.jar' , dest: '/opt/jetty/lib/ext/commons-pool.jar' }
   - { src: '/usr/share/java/mysql.jar' , dest: '/opt/jetty/lib/ext/mysql-connector-java.jar' }
  notify:
   - "Restart Jetty"
  tags: idp

- name: "Check if Shibboleth IdP directory exists and store the result into 'shib_idp_dir' ansible variable"
  stat:
    path: "/opt/shibboleth-idp"
  register: shib_idp_dir
  changed_when: false
  tags: idp

- name: "Be sure that the Shibboleth Identity Provider is downloaded and extracted into the right position"
  unarchive:
    src: "https://shibboleth.net/downloads/identity-provider/{{ shib_idp_version }}/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
    dest: /usr/local/src
    owner: "root"
    group: "root"
    remote_src: True
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that the Shibboleth Identity Provider installer properties' files exists in the right position"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  with_items:
   - { src: "shib-idp-install.properties.j2", dest: "/tmp/shib-idp-install.properties", mode: "0644" }
   - { src: "installer.properties.j2", dest: "/tmp/installer.properties", mode: "0644" } 
   - { src: "shib-idp-persistentId-db.sql.j2", dest: "/root/shib-idp-persistentId-db.sql", mode: "0600" }
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that Apache2 and Jetty are configured to expone the Shibboleth IdP"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: 0644
  with_items:
   - { src: "files/jstl-1.2.jar", dest: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/webapp/WEB-INF/lib/jstl-1.2.jar" }
   - { src: "files/idp.conf", dest: "/etc/apache2/sites-enabled/idp.conf" }
   - { src: "files/idp.xml", dest: "/opt/jetty/webapps/idp.xml" }
  notify:
   - "Restart Apache"
   - "Restart Jetty"
  tags: idp 

- name: "Be sure to install Shibboleth IdP"
  shell: "./install.sh -Didp.property.file=/tmp/installer.properties"
  args:
    chdir: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/bin"
  environment:
    JAVA_HOME: "{{ java_home_dir }}"
  notify:
    - "Restart Jetty"
    - "Restart Apache"
  when: shib_idp_dir.stat.isdir is undefined
  tags: idp

- name: "Be sure that the Shibboleth IdP directories have the right permissions"
  file:
    path: "/opt/shibboleth-idp/{{ item }}"
    owner: "jetty"
    recurse: "yes"
    state: directory
  with_items:
    - logs
    - metadata
    - credentials
    - conf
    - system
    - war
  tags: idp

- name: "Check if 'shibboleth' DB is already created and store the result into 'shib_db' ansible variable"
  command: mysql -u root -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='shibboleth'"
  register: shib_db
  changed_when: false
  tags: idp

- name: "Be sure that the persistent identifiers 'shibboleth' database is created"
  mysql_db:
    encoding: "utf8"
    state: import
    name: all
    target: /root/shib-idp-persistentId-db.sql
  when: shib_db.stdout != 'shibboleth'
  tags: idp

- name: "Be sure that the IdP is configured correctly - Part 1"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "jetty"
    group: "root"
    mode: 0600
  with_items:
   - { src: "saml-nameid.properties.j2", dest: "/opt/shibboleth-idp/conf/saml-nameid.properties" }
   - { src: "global.xml.j2", dest: "/opt/shibboleth-idp/conf/global.xml" }
   - { src: "idp.properties.j2", dest: "/opt/shibboleth-idp/conf/idp.properties" }
   - { src: "ldap.properties.j2", dest: "/opt/shibboleth-idp/conf/ldap.properties" }
   - { src: "metadata-providers.xml.j2", dest: "/opt/shibboleth-idp/conf/metadata-providers.xml" }
  notify:
    - "Restart Jetty"
  tags: idp

- name: "Be sure that the IdP is configured correctly - Part 2"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "root"
   mode: 0600
  with_items:
   - { src: "files/saml-nameid.xml", dest: "/opt/shibboleth-idp/conf/saml-nameid.xml" }
   - { src: "files/subject-c14n.xml", dest: "/opt/shibboleth-idp/conf/c14n/subject-c14n.xml" }
   - { src: "files/logback.xml", dest: "/opt/shibboleth-idp/conf/logback.xml" }
   - { src: "files/attribute-resolver-v3-custom.xml", dest: "/opt/shibboleth-idp/conf/attribute-resolver-v3-custom.xml" }
   - { src: "files/attribute-filter-v3-custom.xml", dest: "/opt/shibboleth-idp/conf/attribute-filter-v3-custom.xml" }
   - { src: "files/services.xml", dest: "/opt/shibboleth-idp/conf/services.xml" }
  notify:
    - "Restart Jetty"
  tags: idp
