---
# tasks file for mysql
- name: "Be sure that 'debconf-utils' package is installed"
  apt:
   name: "debconf-utils"
   state: latest
   update_cache: yes
  notify:
   - "Safe Upgrade"
  tags: mysql

- name: "Check if debconf-get-selections has parameters for unattended mysql installation and store the result on 'debconf' ansible variable"
  shell: (debconf-get-selections | grep -q -s mysql-server); echo $?
  register: debconf
  ignore_errors: yes
  changed_when: false
  tags: mysql 

- name: "Be sure that MYSQL unattented installation debconf's parameters are set correctly"
  debconf:
    name: "mysql-server"
    question: "{{ item.question }}"
    vtype: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - question: mysql-server/root_password
      type: password
      value: "{{ mysql_root_password }}"
    - question: mysql-server/root_password_again
      type: password
      value: "{{ mysql_root_password }}"
  when: debconf.stdout == "1"
  tags: mysql

- name: "Be sure that Mysql and the needed libraries are installed"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: yes
  notify:
   - "Safe Upgrade"
  with_items:
   - python-mysqldb
   - mysql-server
   - libmysql-java
   - libcommons-dbcp-java
   - libcommons-pool-java
   - automysqlbackup
  tags: mysql

- name: "Be sure that .my.cnf file is present for MySQL authentication"
  template: 
    src: "root.cnf.j2" 
    dest: "~/.my.cnf"
    mode: 0600
  tags: mysql

- name: "Be sure that MySQL is up and running"
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql

- name: "Be sure that all root accounts receive the root password for database"
  mysql_user: 
   name: "root" 
   host: "{{ item }}" 
   password: "{{ mysql_root_password }}"
   state: present
  with_items:
     - "{{ fqdn }}"
     - 127.0.0.1
     - ::1
     - localhost
  tags: mysql
