---
# tasks file for mysql
- name: "Be sure that 'debconf-utils' package is installed"
  become: yes
  become_method: sudo
  apt:
   name: "debconf-utils"
   update_cache: yes
   state: latest
  tags: mysql

- name: "Check if debconf-get-selections has parameters for unattended mysql installation and store the result on 'debconf' ansible variable"
  become: yes
  become_method: sudo
  shell: (debconf-get-selections | grep -q -s mysql-server); echo $?
  register: debconf
  ignore_errors: yes
  tags: mysql 

- name: "Be sure that debconf MYSQL unattented installation parameters are set"
  become: yes
  become_method: sudo
  debconf:
    name: "mysql-server"
    question: "{{ item.question }}"
    vtype: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - question: mysql-server/root_password
      type: password
      value: "{{ root_db_password }}"
    - question: mysql-server/root_password_again
      type: password
      value: "{{ root_db_password }}"
  when: debconf.stdout == "1"
  tags: mysql

- name: "Be sure that Mysql and the needed libraries are installed"
  become: yes
  become_method: sudo
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: yes
  with_items:
   - python-mysqldb
   - mysql-server
   - libmysql-java
   - libcommons-dbcp-java
   - libcommons-pool-java
  tags: mysql

- name: "Be sure that .my.cnf file is present for MySQL authentication"
  become: yes
  become_method: sudo
  template: 
    src: "root.cnf.j2" 
    dest: "~/.my.cnf"
    mode: 0600
  tags: mysql

- name: "Be sure that MySQL is up and running"
  become: yes
  become_method: sudo
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql

- name: "Be sure that all root accounts receive the root password for database"
  become: yes
  become_method: sudo
  mysql_user: 
   name: "root" 
   host: "{{ item }}" 
   password: "{{ root_db_password }}"
   state: present
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  tags: mysql
