---
# tasks file for jetty

- name: "Check what Java version is installed and store the result on 'java_version' ansible variable"
  shell: java -version 2>&1 | grep -i version | sed 's/.*version ".*\.\(.*\)\..*"/\1/; 1q'
  register: java_version
  changed_when: false
  tags: jetty 

- name: "Include jetty default variables"
  include_vars:
    file: "java{{ java_version['stdout'] }}_jetty_vars.yml"
  when: jetty_distribution is undefined or jetty_distribution == ""
  tags: jetty 

- name: "Create 'jetty' group"
  group: 
   name: "jetty"
   state: present
  tags: jetty

- name: "Create 'jetty' user"
  user: 
   name: "jetty"
   groups: "jetty"
   createhome: "no"
  tags: jetty

- name: "Extract Jetty Package"
  unarchive:
   src: "files/{{ ansible_os_family }}/java{{ java_version['stdout'] }}/{{ jetty_distribution }}.tar.gz"
   dest: "/usr/local/src"
   owner: "jetty"
   group: "jetty"
  tags: jetty

- name: "Create useful links used by Jetty"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/local/src/{{ jetty_distribution }}' , dest: '/usr/local/src/jetty-src' }
   - { src: '/usr/local/src/jetty-src/bin/jetty.sh' , dest: '/etc/init.d/jetty' }
  tags: jetty

- name: "Create Jetty's directories"
  file:
   path: "{{ item }}"
   owner: "jetty"
   group: "jetty"
   state: directory
  with_items:
   - /opt/jetty
   - /opt/jetty/etc
   - /opt/jetty/lib
   - /opt/jetty/lib/ext
   - /opt/jetty/logs
   - /opt/jetty/resources
   - /opt/jetty/webapps
   - /opt/jetty/tmp
   - /var/log/jetty
  tags: jetty
  
- name: "Configure Jetty"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
  with_items:
   - { src: "files/{{ ansible_os_family }}/java{{ java_version['stdout'] }}/jetty", dest: '/etc/default/jetty' }
   - { src: "files/{{ ansible_os_family }}/java{{ java_version['stdout'] }}/start.ini", dest: '/opt/jetty/start.ini' }
   - { src: "files/{{ ansible_os_family }}/java{{ java_version['stdout'] }}/jetty.xml", dest: '/opt/jetty/etc/jetty.xml' }
  tags: jetty

- name: "Check that 'jetty.service' exists"
  stat: 
   path: /run/systemd/generator.late/jetty.service
  register: jetty_service
  tags: jetty

- name: "Be sure that Jetty is bootable at boot time"
  shell: "update-rc.d jetty defaults"
  when: jetty_service.stat.exists == False
  tags: jetty

- name: "Enable Jetty service"
  service:
    name: jetty
    enabled: yes
  tags: jetty

- name: "Start Jetty service"
  service:
    name: jetty
    state: started
  tags: jetty
