---
# tasks file for jetty
- name: "Be sure that Jessie Backports are installed"
  become: yes
  become_method: sudo
  apt_repository:
   repo: "deb http://ftp.de.debian.org/debian jessie-backports main"
   state: present
   update_cache: yes
  tags: jetty

- name: "Install Java 8"
  become: yes
  become_method: sudo
  apt:
   name: "openjdk-8-jdk"
   state: latest
   update_cache: yes
   cache_valid_time: 3600
  notify:
   - "Restart Jetty"
  tags: jetty

- name: "Be sure that 'default-java' is defined correctly"
  become: yes
  become_method: sudo
  file:
   src: "/usr/lib/jvm/java-8-openjdk-amd64"
   dest: "/usr/lib/jvm/default-java"
   owner: "root"
   group: "root"
   state: link
  tags: jetty   

- name: "Be sure that jetty is installed"
  become: yes
  become_method: sudo
  apt: 
   name: "jetty9"
   state: latest
   update_cache: yes
   cache_valid_time: 3600
  tags: jetty

- name: "Be sure that /etc/default/jetty9 is well configured"
  become: yes
  become_method: sudo
  copy:
   src: "files/jetty"
   dest: "/etc/default/jetty9"
   owner: "root"
   group: "root"
   mode: "0644"
   backup: "yes"
  notify:
   - "Restart Jetty"
  tags: jetty

- name: "Be sure that Jetty is enabled and running"
  become: yes
  become_method: sudo
  service:
    name: jetty9
    state: started
    enabled: yes
  tags: jetty
