---
# tasks file for jetty
- name: "Be sure that Jessie Backports are installed"
  apt_repository:
   repo: "deb http://ftp.de.debian.org/debian jessie-backports main"
   state: present
   update_cache: yes
  tags: jetty

- name: "Be sure that OpenJDK 8 is installed"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: yes
   cache_valid_time: 3600
   default_release: "{{ansible_distribution_release}}-backports"
  with_items:
   - ca-certificates-java
   - openjdk-8-jdk
  notify:
   - "Restart Jetty"
  tags: jetty

- name: "Be sure that 'default-java' is defined correctly"
  file:
   src: "/usr/lib/jvm/java-8-openjdk-amd64"
   dest: "/usr/lib/jvm/default-java"
   owner: "root"
   group: "root"
   state: link
  tags: jetty   

- name: "Be sure that the last version of jetty9 is installed"
  apt: 
   name: "jetty9"
   state: latest
   update_cache: yes
   cache_valid_time: 3600
  tags: jetty

- name: "Be sure that Jetty is enabled and running"
  service:
    name: jetty9
    state: started
    enabled: yes
  tags: jetty
