---
# handlers file for common
- name: "Restart ntp"
  become: yes
  become_method: sudo
  service: 
   name: ntp 
   state: restarted

- name: "Update Timezone"
  become: yes
  become_method: sudo
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: "APT Update"
  become: yes
  become_method: sudo
  apt:
   update_cache: yes
