---
# handlers file for common
- name: "Restart ntp"
  service: 
   name: ntp 
   state: restarted

- name: "Update Timezone"
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: "APT Update"
  apt:
   update_cache: yes
   cache_valid_time: 3600

- name: "Safe Upgrade"
  apt:
    upgrade: safe
