---
# handlers file for common
- name: "Restart ntp"
  service: 
   name: ntp 
   state: restarted

- name: "Update Timezone"
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: "Safe Upgrade"
  apt:
    upgrade: safe
