---
# tasks file for geant-fticks
- name: "Check that logback.xml exists"
  stat:
   path: "/opt/shibboleth-idp/conf/logback.xml"
  register: idp_logback
  tags: geant_fticks

- name: "Configure logback.xml to send F-Ticks to Géant Monitoring Server (in Italy)"
  template:
   src: "conf/logback.xml.j2"
   dest: "/opt/shibboleth-idp/conf/logback.xml"
   owner: "jetty"
   group: "root"
   mode: "0600"
  when: idp_logback.stat.exists
  tags: geant_fticks

- name: "Reload Shibboleth Logging Service"
  command: "/bin/sh /opt/shibboleth-idp/bin/reload-service.sh -id shibboleth.LoggingService"
  environment:
   JAVA_HOME: "/usr/lib/jvm/default-java/jre"
  tags: geant_fticks
