---
# tasks for configure_ssl
- name: "Be sure that SSL Certificate is in '/etc/ssl/certs'"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/common/ssl/{{ common['ssl_cert'] }}"
   dest: "/etc/ssl/certs/ssl-cert.crt"
   owner: "root"
   group: "ssl-cert"
   mode: "0644"
  register: ssl_cert

- name: "Be sure that SSL Key is in '/etc/ssl/private'"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/common/ssl/{{ common['ssl_key'] }}"
   dest: "/etc/ssl/private/ssl-cert.key"
   owner: "root"
   group: "ssl-cert"
   mode: "0440"
  register: ssl_key

- name: "Ensure local certs directory exists"
  file:
   state: "directory"
   path: "/usr/local/share/ca-certificates"

- name: "Install CA Certificate"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/common/ssl/{{ common['ca'] }}"
   dest: "/usr/local/share/ca-certificates/cacert.crt"
   owner: "root"
   group: "root"
   mode: "0644"
  register: ssl_ca

- name: "Update cert index"
  shell: "/usr/sbin/update-ca-certificates"
  when: ssl_ca['changed'] == true
