---
# tasks file for common
- name: "Include OS-specific variables if custom ones are not already defined by host_vars"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: common

## ELASTICSEARCH PART
#- name: "Be sure to format correctly the volume, if exists"
#  filesystem:
#   fstype: "{{ hostvars['localhost']['volume_fs'] }}"
#   dev: "{{ hostvars['localhost']['volume_dev'] }}"
#  when:
#   - hostvars['localhost']['volume_dev'] is defined
#   - hostvars['localhost']['volume_dev'] != ""
#   - hostvars['localhost']['volume_fs'] is defined
#   - hostvars['localhost']['volume_fs'] != ""
#  tags: common_vol

#- name: "Be sure to mount the volume on its directory and with its FileSystem type"
#  mount:
#   state: "mounted"
#   src: "{{ hostvars['localhost']['volume_dev'] }}"
#   path: "/data"
#   fstype: "{{ hostvars['localhost']['volume_fs'] }}"
#  when:
#   - hostvars['localhost']['volume_dev'] is defined
#   - hostvars['localhost']['volume_dev'] != ""
#   - hostvars['localhost']['volume_fs'] is defined
#   - hostvars['localhost']['volume_fs'] != ""
#  tags: common_vol
# ELASTICSEARCH PART

- name: "Be sure that the FQDN is configured"
  template:
   src: hosts.j2
   dest: /etc/hosts
   owner: "root"
   group: "root"
   mode: "0644" 
  tags: common

- name: "Be sure to comment out 'manage_etc_host' from /etc/cloud/cloud.cfg"
  lineinfile:
   dest: /etc/cloud/cloud.cfg
   regexp: "manage_etc_hosts"
   line: "#manage_etc_hosts"
   state: present
  tags: common

- name: "Be sure that needed packages are installed"
  apt: 
   name: "{{item}}"
   update_cache: yes
   state: latest
  with_items:
   - ntp
   - ntpdate
   - vim
   - ca-certificates
   - openssl
   - ssl-cert
   - aptitude
   - debconf
   - debconf-utils
   - apt-transport-https
  tags: common

- name: "Be sure to use the preferred mirror for packages"
  replace:
   dest: /etc/apt/sources.list
   regexp: "http[:][/][/]http.debian.net[/]debian"
   replace: "{{ mirror }}"
  tags: common 

- name: "Be sure ntp is configured"
  template: 
   src: ntp.conf.j2
   dest: /etc/ntp.conf
  notify:
    - "Restart ntp"
  tags: common

- name: "Be sure ntpd is running and enabled"
  service: 
   name: ntp
   state: started
   enabled: yes
  tags: common

- name: "Set timezone variable"
  template:
   src: timezone.j2
   dest: /etc/timezone
   owner: "root"
   group: "root"
   mode: "0644"
   backup: "yes"
  notify:
   - "Update Timezone"
  tags: common

- name: "Be sure that CA, SSL Certificate and SSL Key are inside the right '/etc/ssl' directories"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ item.owner }}"
   group: "{{ item.group }}"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/{{ https_cert }}", dest: "/etc/ssl/certs/ssl-cert.crt", owner: "root" , group: "ssl-cert" , mode: "0644"  }
   - { src: "files/{{ https_key }}", dest: "/etc/ssl/private/ssl-cert.key", owner: "root" , group: "ssl-cert" , mode: "0440"  }
  tags: common

- name: "Ensure local certs directory exists"
  file: 
   state: "directory"
   path: "/usr/local/share/ca-certificates"
  tags: common

- name: "Check if the CA is already installed"
  stat:
    path: "/etc/ssl/certs/cacert.pem"
  register: cacert
  tags: common

- name: "Install CA Certificate"
  copy: 
   src: "files/{{ ca }}"
   dest: "/usr/local/share/ca-certificates/cacert.crt"
   owner: "root"
   group: "root"
   mode: "0644"
  when: cacert.stat.islnk is not defined
  tags: common

- name: "Update cert index"
  shell: "/usr/sbin/update-ca-certificates"
  when: cacert.stat.islnk is not defined
  tags: common
