---
# tasks file for common

#- debug:
#   var: "{{ item }}"
#  with_items:
#   - my_timezone 
#   - ntp1
#   - ntp2
#   - ntp3

- name: "Be sure that the FQDN is configured"
  template:
   src: hosts.j2
   dest: /etc/hosts
   owner: "root"
   group: "root"
   mode: "0644" 
  tags: common

- name: "Be sure to comment out 'manage_etc_host' from /etc/cloud/cloud.cfg "
  lineinfile:
   dest: /etc/cloud/cloud.cfg
   regexp: "manage_etc_hosts"
   line: "#manage_etc_hosts"
   state: present

- name: "Be sure that needed packages are installed"
  apt: 
   name: "{{item}}"
   state: latest
   update_cache: yes
   cache_valid_time: 3600
  with_items:
   - ntp
   - ntpdate
   - vim
   - ca-certificates
   - openssl
   - ssl-cert
   - aptitude
   - debconf
   - debconf-utils
  tags: common

- name: "Be sure to work with the last updated packages (safe-upgrade)"
  apt:
    upgrade: safe
  tags: common

- name: "Be sure ntp is configured"
  template: 
   src: ntp.conf.j2
   dest: /etc/ntp.conf
  notify:
    - "Restart ntp"
  tags: common

- name: "Be sure ntpd is running and enabled"
  service: 
   name: ntp
   state: started
   enabled: yes
  tags: common

- name: "Set timezone variable"
  template:
   src: timezone.j2
   dest: /etc/timezone
   owner: "root"
   group: "root"
   mode: "0644"
   backup: "yes"
  notify:
   - "Update Timezone"
  tags: common

- name: "Be sure that CA, SSL Certificate and SSL Key are inside the right '/etc/ssl' directories"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ item.owner }}"
   group: "{{ item.group }}"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/{{ ca }}", dest: "/etc/ssl/certs/cacert.pem", owner: "root" , group: "root" , mode: "0644"  }
   - { src: "files/{{ https_cert }}", dest: "/etc/ssl/certs/ssl-cert.crt", owner: "root" , group: "ssl-cert" , mode: "0644"  }
   - { src: "files/{{ https_key }}", dest: "/etc/ssl/private/ssl-cert.key", owner: "root" , group: "ssl-cert" , mode: "0440"  }
  tags: common
