---
# tasks file for common

#- debug:
#   var: "{{ item }}"
#  with_items:
#   - my_timezone 
#   - ca
#   - https_cert
#   - https_key 
#   - https_domain
#   - ntp1
#   - ntp2
#   - ntp3

- name: "Be sure that the FQDN is configured"
  become: yes
  become_method: sudo
  template:
   src: hosts.j2
   dest: /etc/hosts
   owner: "root"
   group: "root"
   mode: "0644" 
  notify:
   - "Update FQDN"
  tags: common

- name: "Be sure to comment out 'manage_etc_host' from /etc/cloud/cloud.cfg "
  become: yes
  become_method: sudo
  lineinfile:
   dest: /etc/cloud/cloud.cfg
   regexp: "manage_etc_hosts"
   line: "#manage_etc_hosts"
   state: present

- name: "Be sure that ntp, ntpdate, vim, ca-certificates, openssl, apache2 and expat are installed"
  become: yes
  become_method: sudo
  apt: 
   name: "{{item}}"
   state: latest
   update_cache: yes
  with_items:
   - ntp
   - ntpdate
   - vim
   - ca-certificates
   - openssl
   - apache2
   - expat
   - aptitude
  tags: common

- name: "Be sure to work with the last updated packages (safe-upgrade)"
  become: yes
  become_method: sudo
  apt:
    upgrade: safe
  tags: common

- name: "Be sure ntp is configured"
  become: yes
  become_method: sudo
  template: 
   src: ntp.conf.j2
   dest: /etc/ntp.conf
  notify:
    - restart ntp
  tags: common

- name: "Be sure ntpd is running and enabled"
  become: yes
  become_method: sudo
  service: 
   name: ntp
   state: started
   enabled: yes
  tags: common

- name: "Set timezone variable"
  become: yes
  become_method: sudo
  template:
   src: timezone.j2
   dest: /etc/timezone
   owner: "root"
   group: "root"
   mode: "0644"
   backup: "yes"
  notify:
   - "Update Timezone"
  tags: common
   
- name: "Create /root/certificates directory"
  become: yes
  become_method: sudo
  file:
   path: /root/certificates
   state: directory
   owner: "root"
   group: "root"
   mode: "0755"
  tags: https

- name: "Copy the HTTPS Server certificate to the /root/certificates"
  become: yes
  become_method: sudo
  copy:
   src: "files/{{ https_cert }}"
   dest: /root/certificates
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"
  tags: https

- name: "Copy the HTTPS Server Key to the /root/certificates"
  become: yes
  become_method: sudo
  copy:
   src: "files/{{ https_key }}"
   dest: /root/certificates
   owner: "root"
   group: "root"
   mode: "0400"
  notify:
   - "Restart Apache"
  tags: https

- name: "Copy the CA Certificate to the /root/certificates"
  become: yes
  become_method: sudo
  copy:
   src: "files/{{ ca }}"
   dest: /root/certificates
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"
  tags: https

- name: "Configure Apache SSL"
  become: yes
  become_method: sudo
  template:
   src: default-ssl.conf.j2
   dest: /etc/apache2/sites-enabled/default-ssl.conf
   owner: "root"
   group: "root"
   mode: "0644" 
  notify:
   - "Restart Apache"
  tags: https

- name: "Enable SSL module"
  become: yes
  become_method: sudo
  apache2_module:
   name: "{{ item }}"
   state: present
  with_items:
   - proxy_http
   - ssl
   - headers
  notify:
   - "Restart Apache"
  tags: https

- name: "Disable HTTP site"
  become: yes
  become_method: sudo
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
   - "Restart Apache"
  tags: https

- name: "Disable HTTP port"
  become: yes
  become_method: sudo
  replace:
   dest: /etc/apache2/ports.conf
   regexp: "^Listen 80"
   replace: "#Listen 80"
  notify:
   - "Restart Apache"
  tags: https
