---
# tasks file for check_mk-install
- name: "Be sure that packages needed are installed"
  apt:
   name: "{{ check_mk_agent_packages }}"
   state: latest
   update_cache: yes
  notify:
   - "Safe Upgrade"
  tags: check_mk_agent

- name: "Check if the Monitoring Agent of Check_MK is already downloaded"
  stat:
    path: "/usr/local/src/{{ check_mk_agent_version }}.deb"
  register: agent
  tags: check_mk_agent

- name: "Download the Check_MK monitoring agent for Debian"
  get_url:
   url: "{{ check_mk_agent_dl_url }}"
   dest: "/usr/local/src"
  when: agent.stat.exists == False 
  tags: check_mk_agent

- name: "Install Check_MK Agent"
  command: "gdebi /usr/local/src/{{ check_mk_agent_version }}.deb -n"
  when: agent.stat.exists == False 
  tags: check_mk_agent
