---
# Install OpenJDK on Debian
- name: "Be sure to install OpenJDK 8 backports APT repository"
  apt_repository:
    repo: "deb http://ftp.debian.org/debian jessie-backports main"
    state: present
    update_cache: "yes"
    filename: 'jessie-backports'
  when: jdk_version == "8" and ansible_distribution_release == "jessie"

- name: "Be sure to install OpenJDK 7"
  apt:
   name: "default-jdk"
   state: latest
   update_cache: "yes"
  notify:
   - "Safe Upgrade"
  when: jdk_version == "7" and ansible_distribution_release == "jessie"

- name: "Be sure to install OpenJDK 8"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: "yes"
   default_release: "jessie-backports"
  notify:
   - "Safe Upgrade"
  with_items:
   - "ca-certificates-java"
   - "openjdk-8-jre-headless"
   - "openjdk-8-jre"
   - "openjdk-8-jdk"
  when: jdk_version == "8" and ansible_distribution_release == "jessie"

- name: "Be sure to set the default-java link"
  file:
   src: "/usr/lib/jvm/java-8-openjdk-amd64"
   dest: "/usr/lib/jvm/default-java"
   state: link
  when: jdk_version == "8" and ansible_distribution_release == "jessie"
