---
# Install OpenJDK on Debian
- name: "Be sure to install OpenJDK 8 backports APT repository"
  apt_repository:
    repo: "deb http://ftp.debian.org/debian jessie-backports main"
    state: present
    update_cache: "yes"
    filename: 'jessie-backports'
  when: jdk_version == "8" and ansible_distribution_release == "jessie"
  tags: jdk

#- name: "Check JDK is already present and store the result into 'jdk_link' ansible variable"
#  stat:
#    path: "/usr/lib/jvm/default-java"
#  register: jdk_link
#  changed_when: false
#  tags: jdk

#- name: "Run an APT Update"
#  apt:
#    update_cache: yes
#  notify:
#   - "Safe Upgrade"
#  when: jdk_link.stat.islnk is not defined
#  tags: jdk

- name: "Be sure to install OpenJDK 7"
  apt:
   name: "default-jdk"
   state: latest
   update_cache: "yes"
  notify:
   - "Safe Upgrade"
  when: jdk_version == "7" and ansible_distribution_release == "jessie"
  tags: jdk

- name: "Be sure to install OpenJDK 8"
  apt:
   name: "{{ item }}"
   state: latest
   update_cache: "yes"
   default_release: "jessie-backports"
  notify:
   - "Safe Upgrade"
  with_items:
   - "ca-certificates-java"
   - "openjdk-8-jre-headless"
   - "openjdk-8-jre"
   - "openjdk-8-jdk"
  when: jdk_version == "8" and ansible_distribution_release == "jessie"
  tags: jdk

- name: "Be sure to set the default-java link"
  file:
   src: "/usr/lib/jvm/java-8-openjdk-amd64"
   dest: "/usr/lib/jvm/default-java"
   state: link
  when: jdk_version == "8" and ansible_distribution_release == "jessie"
  tags: jdk
