---
# file: group_vars/Debian.yml
jetty_distribution: "jetty-distribution-9.2.19.v20160908"

java_home_dir: "/usr/lib/jvm/java-7-openjdk-amd64/jre"

openldap_server_pkgs:
  - openldap-servers
  - openldap-clients
  - libselinux-python
  - openssl

openldap_server_app_path: "/etc/openldap/"
openldap_server_user: ldap
